baseURL = 'https://annablsantos.github.io/hugoproject.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-blog-awesome'

[Languages.pt-br.params.author]
  avatar = "unipe_logo.jfif"

  intro = "O projeto introdutório de Hugo :)"

  name = "Anna Beatriz, Thiago Raphael, Francisco Azineu, Haydée Laiz"

  description = "Projeto feito utilizando Hugo, um gerador de sites estáticos escrito em Go."
  [Languages.pt-br.menu]
  [[Languages.pt-br.menu.main]]
    pageRef="/"
    name = 'Início'
    url = '/'
    weight = 10
  [[Languages.pt-br.menu.main]]
    pageRef="posts"
    name = 'Publicações'
    url = '/br/posts/post/'
    weight = 20
